apiVersion: v1
kind: Pod
metadata:
  name: misp-core
spec:
  containers:
  - name: misp-core
    image: ghcr.io/misp/misp-docker/misp-core:latest
    env:
    - name: BASE_URL
      value: https://misp.daan.nl
    - name: MYSQL_USER
      value: misp-db
    - name: MYSQL_PASSWORD
      value: normalpass
    - name: MYSQL_HOST
      value: misp-db
    - name: MYSQL_DATABASE
      value: misp
    - name: MYSQL_PORT
      value: 3306
    volumeMounts:
    - name: misp-config-volume
      mountPath: /var/www/MISP/app/Config/
  volumes:
  - name: misp-config-volume
    hostPath:
      # directory location on host
      path: /media/misp/config
      # this field is optional
      type: Directory
