apiVersion: v1
kind: Pod
metadata:
  name: misp-{{ item[0].name }}-modules
spec:
  containers:
  - name: misp-{{ item[0].name }}-modules
    image: ghcr.io/misp/misp-docker/misp-modules:latest
    env:
    - name: REDIS_BACKEND
      value: redis
