---
- name: Clear old MISP Configs
  ansible.builtin.file:
    state: absent
    path: /etc/containers/systemd/misp

- name: Creates MISP server directory
  ansible.builtin.file:
    path: /etc/containers/systemd/misp/
    state: directory

- name: Creates MISP server directories
  ansible.builtin.file:
    path: /etc/containers/systemd/misp/{{ item.name }}
    state: directory
  loop: "{{ misp_servers}}"

- name: Creates MISP media directories
  ansible.builtin.file:
    path: /media/misp/misp-{{ item[0].name  }}/{{ item[1] }}
    state: directory
  with_nested:
    - "{{ misp_servers }}"
    - ['files', 'db', 'config', 'gnupg', 'logs', 'certs']

- name: Creates MISP Proxy media directories
  ansible.builtin.file:
    path: /media/misp/misp-proxy/
    state: directory

- name: Install MISP kube files
  template:
    src: "{{ item[1].name }}/misp-{{ item[1].name }}.kube.j2"
    dest: /etc/containers/systemd/misp/{{ item[0].name }}/misp-{{ item[0].name }}-{{ item[1].name }}.kube
  become: yes
  with_nested:
    - "{{ misp_servers }}"
    - "{{ misp_files }}"

- name: Install MISP yaml files
  template:
    src: "{{ item[1].name }}/misp-{{ item[1].name }}.yml.j2"
    dest: /etc/containers/systemd/misp/{{ item[0].name }}/misp-{{ item[0].name }}-{{ item[1].name }}.yml
  become: yes
  with_nested:
    - "{{ misp_servers }}"
    - "{{ misp_files }}"

- name: Install MISP network files
  template:
    src: "network/misp.network.j2"
    dest: /etc/containers/systemd/misp/{{ item.name }}/misp-{{ item.name }}.network
  become: yes
  loop: "{{ misp_servers }}"

- name: Install MISP app files
  template:
    src: "misp.service.j2"
    dest: /etc/systemd/system/misp-{{ item.name }}.service
  become: yes
  loop: "{{ misp_servers }}"

- name: Install MISP config files
  copy:
    src: "config/misp-{{ item.name }}/"
    dest: /media/misp/misp-{{ item.name }}/config/
  become: yes
  ignore_errors: true #Some files are not present so we can ignore those errors`
  loop: "{{ misp_servers }}"

- name: Install MISP taxonomy files
  copy:
    src: "taxonomies/{{ item.1 }}/"
    dest: /media/misp/misp-{{ item.0.name }}/files/taxonomies/{{ item.1  }}/
  become: yes
  ignore_errors: true #Some files are not present so we can ignore those errors`
  loop: "{{ misp_servers | subelements('taxonomies', 'skip_missing=True') }}"

- name: Install NGINX systemd
  template:
    src: "nginx/nginx.kube.j2"
    dest: /etc/containers/systemd/misp-proxy.kube
  become: yes

- name: Install NGINX systemd
  template:
    src: "nginx/nginx.yml.j2"
    dest: /etc/containers/systemd/misp-proxy.yml
  become: yes

- name: Install MISP nginx configs
  template:
    src: "nginx/misp.conf.j2"
    dest: /media/misp/misp-proxy/misp-{{ item.name }}.conf
  become: yes
  loop: "{{ misp_servers }}"

