---
- name: Clear old MISP Configs
  ansible.builtin.file:
    state: absent
    path: /etc/containers/systemd/misp
- name: Creates MISP server directory
  ansible.builtin.file:
    path: /etc/containers/systemd/misp/
    state: directory
- name: Creates MISP server directories
  ansible.builtin.file:
    path: /etc/containers/systemd/misp/{{ item.name }}
    state: directory
  loop: "{{ misp_servers }}"
- name: Install MISP kube files
  template:
    src: "{{ item[1].name }}/misp-{{ item[1].name }}.kube.j2"
    dest: /etc/containers/systemd/misp/{{ item[0].name }}/misp-{{ item[0].name }}-{{ item[1].name }}.kube
  become: yes
  with_nested:
    - "{{ misp_servers }}"
    - "{{ misp_files }}"
- name: Install MISP yaml files
  template:
    src: "{{ item[1].name }}/misp-{{ item[1].name }}.yml.j2"
    dest: /etc/containers/systemd/misp/{{ item[0].name }}/misp-{{ item[0].name }}-{{ item[1].name }}.yml
  become: yes
  with_nested:
    - "{{ misp_servers }}"
    - "{{ misp_files }}"
- name: Install MISP network files
  template:
    src: "network/misp.network.j2"
    dest: /etc/containers/systemd/misp/{{ item.name }}/misp.network
  become: yes
  loop: "{{ misp_servers}}"
